version: '3.8'

services:
  db:
    image: postgres:17
    container_name: lab4_db
    environment:
      POSTGRES_USER: lab4user
      POSTGRES_PASSWORD: lab4pass
      POSTGRES_DB: lab4db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab4user -d lab4db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lab4_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab4db
      SPRING_DATASOURCE_USERNAME: lab4user
      SPRING_DATASOURCE_PASSWORD: lab4pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: lab4-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: lab4_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
